#mkdir ios
cd ios
cmake -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DWEBP_BUILD_DWEBP=0 -DWEBP_BUILD_CWEBP=0 \
  -DWEBP_BUILD_IMG2WEBP=0 -DWEBP_BUILD_WEBPINFO=0 \
  -DWEBP_BUILD_WEBPMUX=0 -DWEBP_BUILD_EXTRAS=0 \
  -DENABLE_OPT=0
